- name: Set authorized keys
  authorized_key:
    user: mckyla
    key: "{{ item }}"
  with_items:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpzMpLie8rizcWVkuoURvlPQIczvf0QzqDVmpyNSJSBidSYG+0uXRsVhNPtOoUlwb8FamtAWfE7Ulsp0O/mR+Z6abLBGsI/g/asMaOZSpzS+liHDuw4JjISLLuFKSrKH8Nix5pdr0VLIwZGOCWimWoIm55edcCoUvptrFZB+qlthVK6tlCvA24GGcQ94fWd4WcChBCZJvmQSWGbN6m/mC50xvnvsAL5IZqcjD+iTN+LIDbPSjRmlHTMYw5TUT+PWyq2oBaldkNQ7zAVG88RQ37nyWZ6ze3QQdj3BOvZO72hzrfBaPJBYQGC/p0wkQc0zgffrGRqB8fMIZKP30aCTxX"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBnuTwZ89TaN9lvJCBDaK47/Dra57DsoGKL5Sprerrtg"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICiDTf6MScq30ja1ZHgTmHhANwegiau/FD2kqOnNFZS1"
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC77Q5AKCd5UsdKKPXfN89xobbCKGo2bx6YEUuO1lPWMZ1GTOuhUV+G2Jl3D0aAfNxv3HjYqjY2JDx+r8TCwrWeR0Ej7ecFm/RlHZjxd9XJRW+DNcIRY+eSn/cBw/EzI7M+o8+GGvVHQ2X5IfG3be+o0H/6frYCywxCQSl+DSkVCYIYvIp5CK+jGkSbIYXMNBGhzCeTuZP/tysJf8DK+c/ixPoe0Efzn1If2/wQj5VGbOirz7s+bOqvM4GUh1SEaQuR9KpqSdHJts+PPMbzfQiE82DxDHTuwxfwaIqpYOr3QjqKAfXRxWUpS2GeMtD2wtzMGkbc2UEN6obLwKWrfhitIBlFhp417n+djbiiQQfQQ51nNHMqKBXN2M4AQc+GNQvf32T9zueSdbT6G1KWfEKJJ5vH2hwHS3nHoRX0q+UgSuFz4hytrWPT/xatFWMhnS1sKnN7/ePORXJX6lXpexBYiJ7ymV/yKHt40MZ4rVezbMOJIEHnN4O5L2WaTxHv0KU="
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJpxpQz0ywQZsnuIbds0mVOWhpoQSss+7tdCV8SnNdcs"
